webapps2024/payapp/urls.py
from django.urls import path
from .views import AccountDetailView, HomeView, SendPaymentView, TransactionListView, AllAccountsView, AllTransactionsView

app_name = 'payapp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('account/', AccountDetailView.as_view(), name='account_detail'),
    path('send-payment/', SendPaymentView.as_view(), name='send_payment'),
    path('transactions/', TransactionListView.as_view(), name='transaction_list'),
    path('admin/accounts/', AllAccountsView.as_view(), name='all_accounts'),  # For admins
    path('admin/transactions/', AllTransactionsView.as_view(), name='all_transactions'),  # For admins
]

webapps2024/webapps2024/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Django's built-in auth views
    path('register/', include('register.urls')),  # URLs for the register app
    path('', include('payapp.urls')),  # URLs for the payapp app
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapps2024/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Favicon -->
        {% load static %}
        <link rel="icon" href="{% static 'payecash.jpeg' %}" type="image/x-icon">
        <title>PayeCash</title>

        <!-- Head content including Bootstrap and Font Awesome links -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

        <style>
            :root{
                --blue: #1d418b;
                --white: #ffffff;
            }
            body{
                background-color: lightblue;
            }
            h1,h2,h3,h4,h5,h6{
                text-align: center;
            }
            a,
            a:hover{
                text-decoration: none;
                color: var(--white);
            }
            nav{
                background-color: var(--blue);
                height: 13vh;
            }
            #logo{
                width: 8vw;
                height: 3vw;
            }
            main{
                margin-top: 5vh;
            }
            main h2{
                margin: 5vh;
                font-weight: bold;
            }
            nav,
            nav .container,
            nav .container div{
                display: flex;
                justify-content: space-between;
                align-items: center;
            }
            .payment-form .btn-primary {
                background-color: var(--blue);
                border-color: var(--white);
            }
            .table-hover tbody tr:hover {
                background-color: var(--white);
            }
            .btn-light,
            .btn-secondary,
            .btn-secondary:hover {
                background-color: var(--white);
                border-color: var(--blue);
                color: var(--blue);
            }
            .card{
                background-color: var(--blue);
                color: var(--white);
                min-height: 30vh;
            }
            .card-header{
                font-weight: bold;
            }
            .card-body {
                padding: 2rem;
            }
        </style>
    </head>
<body>
<nav>
    <div class="container">
        <a href="{% url 'payapp:home' %}">{% load static %}<img id="logo" src="{% static 'payecash.jpeg' %}" alt="payecash"></a>
        {% if user.is_authenticated %}
        <div>
            <a class="nav-link" href="{% url 'payapp:send_payment' %}">Send Payment</a>
            <a class="nav-link" href="{% url 'payapp:transaction_list' %}">Transactions</a>
        </div>
        <form action="{% url 'logout' %}" method="post" class="form-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-light"><b>Logout</b><i class="fas fa-sign-out-alt"></i></button>
        </form>
        {% endif %}
    </div>
</nav>

<main class="container">
    {% block content %}{% endblock %}
</main>

<!-- Bootstrap and jQuery scripts -->
</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</html>